'use client'

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/navbar";
const inter = Inter({ subsets: ["latin"] });
import Footer from "~/components/footer";
import { useState } from "react";
import { useUserContext } from "~/supports/context/useUserContext";
import { useBagContext } from "~/supports/context/useBagContext";
// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  const [userData, setUserData] = useState(null)
  const [bagTotal, setBagTotal] = useState(null)

  return (
    <html lang="en">
      <body className={inter.className}>
      <useUserContext.Provider value={{userData, setUserData}}>
        <useBagContext.Provider value={{bagTotal, setBagTotal}}>
      <Navbar></Navbar>
      {children}
      <Footer className="fixed bottom-0"></Footer>
      </useBagContext.Provider>
      </useUserContext.Provider>
      </body>
    </html>
  );
}

